services:
  postgres:
    container_name: evokstest_postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'

  web:
    container_name: evokstest_testrunner
    command: >
      sh -c "set -e &&
             cd ./evoks &&
             python manage.py migrate &&
             coverage run manage.py test -v 3 tests/model/ tests/migration/ tests/skosmos/ tests/fuseki/ tests/views/ tests/evoks &&
             coverage report &&
             coverage xml"

  fuseki-dev:
    container_name: evokstest_fuseki-dev
    environment: 
      ADMIN_PASSWORD: 'fuseki_password'
      
  fuseki-live:
    container_name: evokstest_fuseki-live
    environment: 
      ADMIN_PASSWORD: 'fuseki_password'

  skosmos-dev:
    container_name: evokstest_skosmos-dev

  skosmos-live:
    container_name: evokstest_skosmos-live
