services:
  proxy:
    container_name: evokstest_proxy
    depends_on:
      - web
    restart: "no"

  postgres:
    container_name: evokstest_postgres
    restart: "no"

  change-vol-ownership:
    container_name: evokstest_change-vol-ownership
    # Keep container running during tests to ensure proper --exit-code-from functionality
    command: >
      sh -c "(chmod -R 777 /tmp/change-ownership-fuseki-dev && chmod -R 777 /tmp/change-ownership-fuseki-live ; echo $? > /tmp/chmod_exit_status) ; tail -f /dev/null"
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "cat /tmp/chmod_exit_status | grep -q '^0$'"]
      interval: 5s
      retries: 5

  web:
    container_name: evokstest_testrunner
    entrypoint: >
      sh -c "set -e &&
             cd ./evoks &&
             python manage.py migrate &&
             coverage run manage.py test -v 3 tests/model/ tests/migration/ tests/skosmos/ tests/fuseki/ tests/views/ tests/evoks &&
             coverage report &&
             coverage xml"
    depends_on:
      change-vol-ownership:
        condition: service_healthy
    restart: "no"

  fuseki-dev:
    container_name: evokstest_fuseki-dev
    restart: "no"
      
  fuseki-live:
    container_name: evokstest_fuseki-live
    restart: "no"

  skosmos-dev:
    container_name: evokstest_skosmos-dev
    depends_on:
      change-vol-ownership:
          condition: service_healthy
    restart: "no"

  skosmos-live:
    container_name: evokstest_skosmos-live
    depends_on:
      change-vol-ownership:
          condition: service_healthy
    restart: "no"
