title: EVOKS Docs
description: Documentation for EVOKS
theme: just-the-docs

url: https://kit-data-manager.github.io/EVOKS

aux_links:
  Template Repository: https://github.com/kit-data-manager/EVOKS
