name: custom-tests

on:
  push:
    branches-ignore:
      - master
      - main
      - development
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ubuntu-latest

    services:
      dockerdind:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run tests
        run: |
          docker compose -f docker-compose.custom-test.yml build
          docker compose -f docker-compose.custom-test.yml up --abort-on-container-exit --exit-code-from web

      - name: Remove Docker containers
        if: always()
        run: docker compose -f docker-compose.custom-test.yml down

